# Railway deployment configuration for PDFy
# Documentation: https://docs.railway.com/reference/config-as-code

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bin/rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Volume configuration for file storage
[[volumes]]
name = "pdfy-storage"
mountPath = "/app/storage"

# Environment-specific configurations
[environments.production]
[environments.production.variables]
STORAGE_ROOT = "/app/storage"
RAILS_ENV = "production"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"

[environments.production.deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails db:conditional_seed && bin/rails server -b 0.0.0.0 -p $PORT"

[environments.staging]
[environments.staging.variables]
STORAGE_ROOT = "/app/storage"
RAILS_ENV = "staging"

[environments.staging.deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails db:conditional_seed && bin/rails server -b 0.0.0.0 -p $PORT"