# Railway configuration for Web Service (pdfy-web)
# For Worker service, use railway-worker.toml

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails db:conditional_seed && bin/rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3