# Railway configuration for Worker Service (pdfy-worker)
# For Web service, use railway.toml

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bundle exec sidekiq -C config/sidekiq.yml"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckTimeout = 300