development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64) %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64) %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || raise("SECRET_KEY_BASE environment variable is required") %>