name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: production
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Railway
      run: |
        railway up --service=${{ env.SERVICE_ID }} --environment=production --detach

    - name: Health check
      run: |
        sleep 30
        curl -f ${{ secrets.RAILWAY_PUBLIC_URL }}/health || exit 1