name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  RAILWAY_ENVIRONMENT: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH

    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }} --detach

    - name: Health check
      run: |
        sleep 30
        curl -f ${{ secrets.RAILWAY_PUBLIC_URL }}/health || exit 1