name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: production
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Web Service
      run: |
        railway up --service=pdfy-web --environment=production --detach

    - name: Deploy Worker Service  
      run: |
        railway up --service=pdfy-worker --environment=production --detach

    - name: Health check
      run: |
        echo "Web and Worker services deployed successfully!"
        echo "Web service: ${{ secrets.RAILWAY_PUBLIC_URL }}"